# Generated by Django 4.0 on 2022-07-15 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fees',
            name='paid_date',
            field=models.DateField(null=True),
        ),
    ]
