# Generated by Django 4.0.5 on 2022-07-13 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_delete_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fees',
            name='from_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='fees',
            name='to_date',
            field=models.DateField(null=True),
        ),
    ]
